# Generated by Django 5.2.5 on 2025-08-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
