# Generated by Django 5.2.5 on 2025-09-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('reggae', 'Reggae/Riddims'), ('rhumba', 'Rhumba'), ('mugithi', 'Mugithi'), ('rnb', 'RnB'), ('soul', 'Soul')], default='reggae', max_length=50)),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('ticket_link', models.URLField(blank=True)),
                ('spotify_playlist', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
