# Generated by Django 5.2.5 on 2025-09-04 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0006_event_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
    ]
