# Generated by Django 5.2.5 on 2025-09-05 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0007_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='spotify_playlist',
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='TicketOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='playlist.event')),
            ],
        ),
    ]
