# Generated by Django 5.2.5 on 2025-09-05 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0008_alter_event_options_remove_event_spotify_playlist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='price',
        ),
    ]
