# Generated by Django 5.2.5 on 2025-09-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0009_remove_event_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='custom_genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='genre',
            field=models.CharField(choices=[('reggae', 'Reggae/Riddims'), ('rhumba', 'Rhumba'), ('mugithi', 'Mugithi'), ('rnb', 'RnB'), ('soul', 'Soul'), ('other', 'Other')], default='reggae', max_length=50),
        ),
    ]
